// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BentoSearchResultsController from "./bento_search_results_controller"
application.register("bento-search-results", BentoSearchResultsController)

import BentoSearchTotalsController from "./bento_search_totals_controller"
application.register("bento-search-totals", BentoSearchTotalsController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import Email2faAlertController from "./email_2fa_alert_controller"
application.register("email-2fa-alert", Email2faAlertController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RelatedRecordsController from "./related_records_controller"
application.register("related-records", RelatedRecordsController)

import RangeSliderController from "./range_slider_controller"
application.register("range-slider", RangeSliderController)
