require:
  - standard
  - rubocop-rails
  - rubocop-minitest

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - tmp/**/*

Rails:
  Enabled: true
Minitest:
  Enabled: true
Bundler/DuplicatedGem:
  Enabled: false
