require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - tmp/**/*

Rails:
  Enabled: true
Rails/FilePath:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
RSpec:
  Enabled: true
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/Capybara/FeatureMethods:
  Enabled: false
Bundler/DuplicatedGem:
  Enabled: false
