# Place any default configuration for solr_wrapper here
# port: 8983
version: "8.7.0"
cloud: true
collection:
  dir: solr/conf/
  name: blacklight
  persist: false
configsets:
  - dir: solr/conf/
    name: blacklight-configset
