development:
  adapter: solr
  url: <%= ENV['BLACKLIGHT_SOLR_URL'] || 'set BLACKLIGHT_SOLR_URL environment variable' %>
test: &test
  adapter: solr
  url: <%= ENV['BLACKLIGHT_SOLR_URL'] || 'set BLACKLIGHT_SOLR_URL environment variable' %>
production:
  adapter: solr
  url: <%= ENV['BLACKLIGHT_SOLR_URL'] || 'set BLACKLIGHT_SOLR_URL environment variable' %>
