development:
  adapter: solr
  url: <%= ENV['NB_SOLR_URL'] || 'set NB_SOLR_URL environment variable' %>
test: &test
  adapter: solr
  url: <%= ENV['NB_SOLR_URL'] || 'set NB_SOLR_URL environment variable' %>
production:
  adapter: solr
  url: <%= ENV['NB_SOLR_URL'] || 'set NB_SOLR_URL environment variable' %>
