development:
  mapsearch:
    url: "https://mapsearch.nla.gov.au?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://mapsearch.nla.gov.au/search/search?type=map&text="

  nla_shop_url: https://bookshop.nla.gov.au/api/jsonDetails.do
  contact_us_url: https://www.nla.gov.au/using-library/getting-started/ask-librarian

test:
  mapsearch:
    url: "https://mapsearch.nla.gov.au?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://mapsearch.nla.gov.au/search/search?type=map&text="

  nla_shop_url: https://bookshop.nla.gov.au/api/jsonDetails.do
  contact_us_url: https://www.nla.gov.au/using-library/getting-started/ask-librarian

staging:
  mapsearch:
    url: "https://mapsearch.nla.gov.au?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://mapsearch.nla.gov.au/search/search?type=map&text="

  nla_shop_url: https://bookshop.nla.gov.au/api/jsonDetails.do
  contact_us_url: https://www.nla.gov.au/using-library/getting-started/ask-librarian

production:
  mapsearch:
    url: "https://mapsearch.nla.gov.au?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://mapsearch.nla.gov.au/search/search?type=map&text="

  nla_shop_url: https://bookshop.nla.gov.au/api/jsonDetails.do
  contact_us_url: https://www.nla.gov.au/using-library/getting-started/ask-librarian
