development:
  mapsearch:
    url: "https://georekt-test.nla.gov.au/mapsearch/?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "http://georekt-test.nla.gov.au/mapsearch/search/search?type=map&text="

test:
  mapsearch:
    url: "https://georekt-test.nla.gov.au/mapsearch/?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://georekt-test.nla.gov.au/mapsearch/search/search?type=map&text="

staging:
  mapsearch:
    url: "https://mapsearch.nla.gov.au?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://mapsearch.nla.gov.au/search/search?type=map&text="

production:
  mapsearch:
    url: "https://mapsearch.nla.gov.au?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://mapsearch.nla.gov.au/search/search?type=map&text="
