development:
  subnet:
    local: ***REMOVED***
    staff: ***REMOVED***

  mapsearch:
    url: "https://georekt-test.nla.gov.au/mapsearch/?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://georekt-test.nla.gov.au/mapsearch/search/search?type=map&text="

test:
  subnet:
    local: ***REMOVED***
    staff: ***REMOVED***

  mapsearch:
    url: "https://georekt-test.nla.gov.au/mapsearch/?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://georekt-test.nla.gov.au/mapsearch/search/search?type=map&text="

staging:
  subnet:
    local: ***REMOVED***
    staff: ***REMOVED***

  mapsearch:
    url: "https://mapsearch.nla.gov.au?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://mapsearch.nla.gov.au/search/search?type=map&text="

production:
  subnet:
    local: ***REMOVED***
    staff: ***REMOVED***

  mapsearch:
    url: "https://mapsearch.nla.gov.au?type=map&mapClassifications=all&geolocation=all&text="
    search_url: "https://mapsearch.nla.gov.au/search/search?type=map&text="
