x-app: &app
  build:
    context: .
    args:
      RUBY_VERSION: '30'
  image: nla-blacklight:latest
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
    PIDFILE: /tmp/pids/server.pid
  tmpfs:
    - /tmp
    - /tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ..:/opt/app-root/src:cached
    - ./db_init:/docker-entrypoint-initdb.d
    - bundle:/opt/app-root/src/vendor/bundle
    - rails_cache:/opt/app-root/src/tmp/cache
    - node_modules:/opt/app-root/src/node_modules
    - history:/usr/local/hist
    - assets:/opt/app-root/src/public/assets
  environment: &backend_environment
    <<: *env
    REDIS_URL: redis://redis:6379/
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    XDG_DATA_HOME: /opt/app-root/src/tmp/caches
    YARN_CACHE_FOLDER: /opt/app-root/src/node_modules/.yarn-cache
    HISTFILE: /usr/local/hist/.bash_history
    IRB_HISTFILE: /usr/local/hist/.irb_history
    EDITOR: vi
  depends_on: &backend_depends_on
    mysql:
      condition: service_healthy
    solr:
      condition: service_started

services:
  rails: &rails
    <<: *backend
    command: bundle exec rails

  web:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000

  mysql:
    image: mysql:8-oracle
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blight
      MYSQL_USER: blight
      MYSQL_PASSWORD: blight
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      interval: 1s
      timeout: 20s
      retries: 10

#  redis:
#    image: redis:6.2-alpine
#    volumes:
#      - redis:/data
#    ports:
#      - 6379:6379
#    healthcheck:
#      test: redis-cli ping
#      interval: 1s
#      timeout: 3s
#      retries: 10

  solr:
    image: solr:8
    volumes:
      - ../solr:/blacklight_config
    command: solr-precreate blacklight-core /blacklight_config
    environment:
      SOLR_HEAP: 4g
    ports:
      - 8983:8983

volumes:
  bundle:
  node_modules:
  history:
  rails_cache:
  mysql:
  redis:
  assets:
