# This workflow runs the unit and system tests and generates a code coverage report in the
# pull request comment.
#
# It uses the default MySQL database included in the runner (usually ubuntu-latest).
name: "Code test coverage"
on:
  pull_request:
    branches:
      - main
      - release/**
jobs:
  coverage:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: coverage
    runs-on: ubuntu-latest
    env:
      CI: true
      RUBY_VERSION: '3.0.2'
      DB_DATABASE: blacklight_test
      DB_USER: root
      DB_PASSWORD: root
      RAILS_ENV: test
      DATABASE_URL: "mysql2://root:root@localhost:3306/blacklight_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.92
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Set up MySQL
        run: |
          pwd
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Spin up SolrCloud + Zookeeper cluster
        uses: isbang/compose-action@v1.1.0
        with:
          compose-file: "./solr/cloud/docker-compose.yml"
          down-flags: "--volumes"

      - name: Check Zookeeper status
        run: |
          echo "ruok" | nc localhost 2181 ; echo 

      - name: RSpec tests
        run: |
          bundle exec rspec

      - name: Cucumber tests
        run: |
          bundle exec cucumber

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          failedThreshold: 80
          token: ${{ secrets.GITHUB_TOKEN }}
